### PR TITLE
Activity star improvements

### PR DESCRIPTION
**Pull request by Hilarious001**
Hello @jkroepke 
just a small update as with your code, you even have an activity star on the planet when you are trying to hide on moons, this make ninjas really hard and the real ogame times are 
Activity star till 15 min
Timer from 15-60min and then nothing anymore

Regards

### CODE REVIEW

**Comment by jkroepke** [comment]
you remove the $this->galaxyRow['m_last_update'] variables. So times on the moon will be ignored?

**Comment by Hilarious001** [comment]
Yes indeed my mistake i logged back on ogame to see myself its my player sayingn nonsense
anyway i changed it back and simply updated the numbers the timers are shown

**Comment by jkroepke** [comment]
OGame is well documented in a german wiki, for example: http://owiki.de/index.php/Stern

Since I do not have an ogame account, this wiki helps me alot.

**Comment by jkroepke** [comment]
.. and thanks for the pr.

**Pull request merged**
