### PR TITLE
Added contrib docker scripts

### PR DESCRIPTION
**Pull request by daugustin**
Scripts added to automatically run the current git version in 2 docker containers and open it up in the browser.

### CODE REVIEW

**Comment by jkroepke** [comment]
How long takes time to build the docker container? #gentoo

**Comment by daugustin** [comment]
The initial build takes about 15minutes on my i7-4770.

**Comment by OzanKurt** [comment]
What is this?

**Comment by daugustin** [comment]
Just run the script, it will deploy 2 docker containers on your local machine and install the current git version of 2moons on it.

**Comment by OzanKurt** [comment]
Cool! :)

**Comment by jkroepke** [comment]
Do you know about docker?

**Comment by OzanKurt** [comment]
Just heard of it once and today I read its docs but seemed complicated. :/

**Pull request closed without merging**
