### PR TITLE
Fix $costresource research

### PR DESCRIPTION
**Pull request by Hilarious001**
Fix the price of the research

### CODE REVIEW

**Comment by bornhaeusser** [comment]
Now i think it is wrong.
The Cost was the cost from the next level.

**Comment by Hilarious001** [comment]
Not really, use the $costresource on a blank page with a echo you will see you will not get the same amount as its would be expected, this fix the problem. if you use default code, to build level 9 it will ask you the price for the level 8 (that is already build on the planet or maybe in the queu list).
This does fix that issue

Regards

**Comment by sp33d86** [comment]
Also, I think it was fixed wrong here like in case of the buildings.
Again I'm comparing to the original OGame (here without fix):
image
image
Formula from owiki.de:
image
All correct without fix...

**Comment by Hilarious001** [comment]
Hello don't try to understand or say its not true lol, @jkroepke comfirmed the issue and this is a real problem, i am working on this since years, i will not open a pull request if not needed, it has been tested, validated, and comfirmed, with different type of forumlas outside and inside 2moons

If you want to be sure, echo the resource on the overview page from the building in queu and echo the resource on the building page, you will see about what we are talking in here

=> #240

Regards
Hilarious

**Comment by sp33d86** [comment]
Haha, no need to be offensive. I may try to understand whenever I like to, dude! Just relax and calm down.
Also, what I just said was, that with the fix applied, the price for the research was the price for the correct level +1. Just a fact. Without it applied it was just like in the original OGame. Also just a fact.
I only wanted to help and I find your reaction kind of "hilarious" (pun intended)...
So long... and thanks for all the fish. ;)

**Comment by jkroepke** [comment]
See #241 for more informations. This pull request needs to be merged, if I changes the values in the database.

**Comment by jkroepke** [comment]
We need a upgrade/migration path for current games.

**Comment by jkroepke** [comment]
Lets track this issue in #241 I hate to comment both pull requests.

**Comment by Hilarious001** [comment]
Closed #241 
yes whatever you want to name it, i have to do it for my game, so i will post a script this weekend here to

**Pull request merged**
