### PR TITLE
Fixes some stuffs

### PR DESCRIPTION
**Pull request by bergi9**

### CODE REVIEW

**Comment by jkroepke** [comment]
Hi,

did you test your changed while the game was not installed?

I think, the vars,php change maybe break it.

**Comment by bergi9** [comment]
I have the game running. I didn't noticed any breaks by moving the includes of vars.php.

**Comment by jkroepke** [comment]
I will check this and merge this.

**Comment by Hilarious001** [comment]
all what he did is working fine :)

**Comment by jkroepke** [comment]
Thanks!

**Comment by jkroepke** [comment]
Just for notice, this pr break the game, if its not installed.

**Comment by bergi9** [comment]
Yes i have reconized it by installing on a test machine. I will do a pull request again if i have changed it.

**Pull request merged**
