### PR TITLE
Fix $costresource building

### PR DESCRIPTION
**Pull request by Hilarious001**
Fix the price of the buildings

### CODE REVIEW

**Comment by bornhaeusser** [comment]
Now i think it is wrong.
The Cost was the cost from the next level.

**Comment by Hilarious001** [comment]
Not really, use the $costresource on a blank page with a echo you will see you will not get the same amount as its would be expected, this fix the problem. if you use default code, to build level 9 it will ask you the price for the level 8 (that is already build on the planet or maybe in the queu list).
This does fix that issue

Regards

**Comment by sp33d86** [comment]
I don't think that this is correct.
If you compare the former 2moons implementation (without the fix) with the original OGame, you can see that everything is alright:
image
image
Comparing it with the fixed version you will see, that you are asked the price of the next level.
You can also calculate it for the solar power plant manually and you will get (for level 20):
Metal: 50 * 1,5 ^ X = 50 * 1,5 ^ 20 = 166263
Crystal: 20 * 1,5 ^ X = 20 * 1,5 ^ 20 = 66505
Source for the formula: http://www.owiki.de/index.php/Solarkraftwerk

**Comment by Hilarious001** [comment]
Hello don't try to understand or say its not true lol, @jkroepke comfirmed the issue and this is a real problem, i am working on this since years, i will not open a pull request if not needed, it has been tested, validated, and comfirmed, with different type of forumlas outside and inside 2moons

If you want to be sure, echo the resource on the overview page from the building in queu and echo the resource on the building page, you will see about what we are talking in here

Regards
Hilarious

**Comment by sp33d86** [comment]
Haha, no need to be offensive. I may try to understand whenever I like to, dude! Just relax and calm down.
Also, what I just said was, that with the fix applied, the price for the building was the price for the correct level +1. Just a fact. Without it applied it was just like in the original OGame. Also just a fact.
I only wanted to help and I find your reaction kind of "hilarious" (pun intended)...
So long... and thanks for all the fish. ;)

**Comment by jkroepke** [comment]
See #241 for more informations. This pull request needs to be merged, if I changes the values in the database.

**Comment by Hilarious001** [comment]
yes for sure, you need to review all values in database to have again same values as the real ogame, but atleasy the game wil have a bug less, thats the main case, if you want i post you new values in the install file.

Regards

**Comment by Hilarious001** [comment]
Closed #241

**Pull request merged**
