### PR TITLE
Decode accent HTML to UTF-8 format & small spellchecking for FR language

### PR DESCRIPTION
**Pull request by BigTwoProduction**
Hello,

Small changes into FR files:

- Decode accent HTML to UTF-8 format
- Small spellchecking

Best regards,

### CODE REVIEW

**Comment by jkroepke** [comment]
Thanks!

You can still add yourself to the Language authors.

https://github.com/jkroepke/2Moons/blob/master/styles/templates/adm/OverviewBody.tpl#L141

**Comment by BigTwoProduction** [comment]
Hello,

But my name is already added to this files... 
So what you mean by 

> You can still add yourself to the Language authors.

**Comment by jkroepke** [comment]
Your name should be displayed on admin panel, visible for everyone.

**Comment by BigTwoProduction** [comment]
I'm not sure but at this point you have already add me name to this file. So did have to change by my self this file and put PR ?

**Comment by jkroepke** [comment]
Sorry man, I didn't notice that BigTwoProduction are `KickXAss4Ever & Apocalypto2202` 

Nevermind.

**Comment by BigTwoProduction** [comment]
Hello @jkroepke after speaking with BigTwoProduction team we preferred if in this file [https://github.com/jkroepke/2Moons/blob/master/styles/templates/adm/OverviewBody.tpl#L141] the name of BigTwoProduction appear. Can you modify ? Or I made PR, as you want ;)

Regards,
Jordan.

**Comment by jkroepke** [comment]
Changed. 

FYI: I'm changing a lot of language keys now (sorry for that!).

With this change, i'm able to use free translation programs. So translators like you can services like this: https://www.transifex.com/2moons/2moons/dashboard/

I think, it's a big aventage. Translators can be see easy, what keys are missing.

**Comment by BigTwoProduction** [comment]
Ok thanks notice that to me. At this point for French language 54 strings still translate. So tomorrow I will check that mismatch French strings translation and update them ;)

I think this tool [https://www.transifex.com](url) will be very useful for all of us !
One question initial language is Deutsch isn't it ?

Have a nice evening,
Jordan.

**Comment by jkroepke** [comment]
Deutsch / German is the source language and my main language.

**Comment by BigTwoProduction** [comment]
Ok but not enough knowledge for me to translate directly German/French is not possible.
For me it's English to French ;)

**Comment by jkroepke** [comment]
Wow, it's not possible to cross translate from english to french. i didn't notice that

**Comment by BigTwoProduction** [comment]
No it's possible because when I can't translate by myself the English translation ( when string mean nothing) I work with German language and Google translator to create string makes sense.

You are ok with that ? Trust me translate french string are good ;)

**Comment by BigTwoProduction** [comment]
I think you don't understand together. It's just because of my lack skills in German language.

Nevermind ;)

**Comment by jkroepke** [comment]
Maybe transifex isn't the best solution.

**Comment by lilmnm-kamikaze-** [comment]
i think BigTwo means its not possible for him to translate from German to french as he doesn't know German well. He uses google translator to help with the translations to English or french from German to help him understand the string. 

Sorry to butt in. 

But also a part of the translation is grammatical translation which some of the English translations is lacking in so even though its in English, is it still is confusing to read it. Again sorry to bring it up in this issue thread.

**Comment by BigTwoProduction** [comment]
Hello everbody,

Let's me explain a little:

First thing, as said @lilmnm-kamikaze- 

> i think BigTwo means its not possible for him to translate from German to French as he doesn't know German well

So to translate in French language I used English language string.

Second thing, @jkroepke we don't understand together, Transifex is a great tools. I wasn't talking Transiflex but of my method of working.

Sorry for the confusion :)
Jordan.

**Comment by jkroepke** [comment]
Hi,

I understand you correctly. You can't translate German <-> Francis, because you can't German. 

Thats a problem in my opinion, because look at the German <-> English translation to translate English <-> Francis is a dirty hack. 

May you understand to workaround this issue. Other potential translators would be confusied. Thats the problem.

I also have some technical issues with transiflex. They have a badly ingration with github and I wan't to automate to process without update the source files constantly.

Yesterday, I test weblate as alternative, but I don't have a good webinterace.

The next will be Poodle on my list, see http://pootle.locamotion.org/projects/pootle/

**Pull request merged**
