### PR TITLE
Give the possibilities to change nickname

### PR DESCRIPTION
**Pull request by Hilarious001**
Fix the problem that doesnt want to change the nickname of the player

### CODE REVIEW

**Comment by jkroepke** [comment]
Lol., fail.. 

Thanks!

**Comment by BassXX** [comment]
Not working for me :( SQL Error

Message: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined

 Query-Code:UPDATE uni1_users SET username = BassX, uctime = 1461399659t WHERE id = 1;
File: /includes/classes/Database.class.php
Line: 109
URL: http://ddclan.mrtv.biz/game/game.php?page=settings
PHP-Version: 5.5.9-1ubuntu4.14
PHP-API: fpm-fcgi
MySQL-Cleint-Version: mysqlnd 5.0.11-dev - 20120503 - $Id: bf9ad53b11c9a57efdb1057292d73b928b8c5c77 $
2Moons Version: 1.8.git
Debug Backtrace:
#0 /includes/classes/Database.class.php(160): Database->_query('UPDATE %%USERS%...', Array, 'update')
 #1 /includes/pages/game/ShowSettingsPage.class.php(283): Database->update('UPDATE %%USERS%...', Array)
 #2 /includes/pages/game/ShowSettingsPage.class.php(138): ShowSettingsPage->sendDefault()
 #3 /game.php(57): ShowSettingsPage->send()
 #4 {main}

**Comment by jkroepke** [comment]
Search for timestampt and replace it with timestamp on the SettingsPage.php

**Comment by BassXX** [comment]
working now perfect! But how can I change it back again?

**Comment by jkroepke** [comment]
Maybe you can create a pull reqest for this fix, too.?

**Pull request merged**
