### PR TITLE
Simpliest search fix to make search work

### LINKED ISSUE #145: Search not work
Hi, we have not working search. In alliance tab search not work too.

### PR DESCRIPTION
**Pull request by Hilarious001**
Hello guys, just read the code change tome stuff and its fixed #145

### CODE REVIEW

**Comment by jkroepke** [comment]
If you replace ```LIMIT 25``` with LIMIT ```".$maxResult."```, it should be fine.

**Comment by BassXX** [comment]
Hey Guys, thanks for the help! Search is now working for Planets & Players, but unfortunately not for Allies :(

Is there a possibility to fix this?

**Comment by Hilarious001** [comment]
Jan, i had tested it before but it didnt really change the problem, due to this:
:limit'			=> $maxResult
$maxResult === -1 ? '' : 'LIMIT :limit';
and  since i was at work, i quickly posted the easiest way

Regards

**Comment by jkroepke** [comment]
This probleme is, the autocomplete function will be return 25 users, too. Thats too much..

The parameter $limit must be used

**Comment by jkroepke** [comment]
See #183

**Pull request closed without merging**
