### PR TITLE
Fix the possibilities to search alliance

### PR DESCRIPTION
**Pull request by Hilarious001**
Fix the possibilities to search alliance #154

### CODE REVIEW

**Comment by Hilarious001** [comment]
add me skype then will be easier
xterium.support

**Comment by jkroepke** [comment]
Chaging searchText to searchTextt fixed this issue?

**Comment by BassXX** [comment]
Hey there, I am still encountering the issue of not working alliance search.

Maybe you could help me? thank you guys

**Comment by jkroepke** [comment]
Try this: https://github.com/jkroepke/2Moons/pull/156/files

**Comment by BassXX** [comment]
Hey Guys!

Unfortunately it´s still giving me no Results while searching at the search page (Tag and Name).

When searching in the alliance page, i get the following error:

`Message: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens

 Query-Code:SELECT id, ally_name, ally_tag, ally_members FROM uni1_alliance WHERE ally_universe = 1 AND ally_name LIKE %Test% ORDER BY ( IF(ally_name = %Test%t, 1, 0) + IF(ally_name LIKE %Test%, 1, 0) ) DESC,ally_name ASC LIMIT 25;
File: /includes/classes/Database.class.php
Line: 109
URL: http://ddclan.mrtv.biz/game/game.php?page=alliance&mode=search
PHP-Version: 5.5.9-1ubuntu4.14
PHP-API: fpm-fcgi
MySQL-Cleint-Version: mysqlnd 5.0.11-dev - 20120503 - $Id: bf9ad53b11c9a57efdb1057292d73b928b8c5c77 $
2Moons Version: 1.8.git
Debug Backtrace:
#0 /includes/classes/Database.class.php(176): Database->_query('SELECT id, ally...', Array, 'select')
 #1 /includes/pages/game/ShowAlliancePage.class.php(252): Database->select('SELECT id, ally...', Array)
 #2 /game.php(57): ShowAlliancePage->search()
 #3 {main} `

What could I do to fix this?

**Comment by BassXX** [comment]
The ally search is still not working for me :( I don´t know what I am doing wrong. Anybody can help me?

**Comment by jkroepke** [comment]
Look for https://github.com/Hilarious001/2Moons/blob/patch-26/includes/pages/game/ShowAlliancePage.class.php#L245

searchTextt and replace it with searchText

**Comment by BassXX** [comment]
thats the way! Thank you very much. Working now!

**Comment by jkroepke** [comment]
Maybe you can provide a pull request for the quick fix?

**Comment by BassXX** [comment]
sure!

**Comment by BassXX** [comment]
Sorry Jan, Somehow i cannot manage to create a new pull request. I am quite a beginner in using GitHub, so please understand :D

But here is the way, how i fixed it:

1. Changed the original recent file from 2moons master according to: https://github.com/jkroepke/2Moons/pull/156/files

2. Went to Line 245: Changed "searchTextt" to "searchText"

**Comment by BassXX** [comment]
All right, gotcha! Pull request is open now

**Pull request merged**
