### PR TITLE
Stats loop to much giving point of next level

### PR DESCRIPTION
**Pull request by Hilarious001**
Fixing fake stats

### CODE REVIEW

**Comment by jkroepke** [comment]
As you say, the function getElementPrice is wrong.

We should fix this function. #241

**Comment by Hilarious001** [comment]
Hello just to let you know the stats and the costresource are 2 real different errors.

Example:

Costresource function ask you to pay the price for the level you already have instead of the next level
The stat resource add you another extra level on the one you already have

To fix it, i implented this pull request, and i changed on building and research simly $leveltobuild+1 in function show, function addelementtoqueue

**Comment by jkroepke** [comment]
I think, if we real problem is described here: #241

If we adjust the values, This should be fine without changing the logic in includes/classes/class.statbuilder.php

**Comment by jkroepke** [comment]
After fixing #241, is this issue still valid?

**Comment by Hilarious001** [comment]
For sure, lets understand your code

For level 1 to a level inferior or egual to what you have build, then it run an extra for
So you have level 20, it will run till level 21, as there is an extra loop for if its equal to yours thanks to the $Level++
simply need to remove that small = symbol

```
for($Level = 1; $Level <= $USER[$resource[$Techno]]; $Level++)
{
    $TechPoints	+= $Units * pow($pricelist[$Techno]['factor'], $Level);
}
```

If you remove that = symbol
Then it will make a last loop if the level is at 19 to go to 20. and then will stop. so it will get what you realy have,
hope you see what i mean

**Comment by jkroepke** [comment]
Hi!

I asked a friend who is good in math. We optimized the function. Here is our current result:

```
$TechPoints = $Units * $pricelist[$Techno]['factor'] * ( 2 * (pow($pricelist[$Techno]['factor'], $USER[$resource[$Techno]]) - $pricelist[$Techno]['factor']) + 1);
```

Means:

```
Points = (All resources / 1000) * Factor * ( 2 * ( Factor ^ Level ) - Factor) + 1)
```

There is a chance to test this function?

**Comment by Hilarious001** [comment]
for sure, i will test i after my IRL work and give you an update around 23h CET

**Comment by jkroepke** [comment]
Thanks

Hilarious001 <notifications@github.com<mailto:notifications@github.com>> schrieb am Mi., 17. Aug. 2016, 12:09:

for sure, i will test i after my IRL work and give you an update around 23h CET

**Pull request closed without merging**
