### PR TITLE
Update error.default.tpl

### PR DESCRIPTION
**Pull request by Hilarious001**
This help the auto redirect to work again

### CODE REVIEW

**Comment by jkroepke** [comment]
Is this bad. meta tags should be always in the head section.. Use script block for this..

https://github.com/jkroepke/2Moons/blob/master/styles/templates/game/main.header.tpl#L61

**Comment by Hilarious001** [comment]
i have that code, but it never redirect. it stay blocked at the print message and then you have to click a new menu manualy.

With my change and chaning the print message with message true link, all works again, but i gonna add it in the block section under the code np

**Comment by jkroepke** [comment]
Hi,

I must revert this change. First, if no auto redirect , I will get this error: Undefined index: gotoinsec

Secondly, your code is already included at the main.header.tpl, is this not good enough?
https://github.com/jkroepke/2Moons/blob/master/styles/templates/game/main.header.tpl#L18

**Comment by Hilarious001** [comment]
oh yea sorry i use fault pack with alot of change pack so i didnt had this
meta tag with if state in main header anymore

Thats the reason it was not working for me

Thanks to let me know it

Regards

2016-01-09 18:18 GMT+01:00 Jan-Otto Kröpke <notifications@github.com>:

**Pull request merged**
