### PR TITLE
Wrong data in Alliance message

### LINKED ISSUE #265: Wrong data in Alliance message
I received a message from an Ally. From and Date fields contains strange data.

screenshot_20160906 220113

PS: Sorry but i am new to GIT... what happens now? If i fix it how what's the procedure? Thanks

### PR DESCRIPTION
**Pull request by Hilarious001**
Fix #265

### CODE REVIEW

**Comment by jkroepke** [comment]
#308 ?

**Comment by Hilarious001** [comment]
Hello

€307 is ok #308 is an error and should be deleted, didnt find how to

**Comment by jkroepke** [comment]
#307 and #308 are identical.

**Comment by Hilarious001** [comment]
Hello not really,

In 307 you have lng diplo_ask and in 308 lng diplo_war,

so a small error in language text that will be displayed if not diplo 5

**Comment by jkroepke** [comment]
Since you deleted your branch, i can not applied the pr anymore

**Pull request closed without merging**
